import { useSession } from 'next-auth/react'
import Head from 'next/head'
import { useRouter } from 'next/router'
import Dashboard from '../components/Dashboard'
import Loader from '../components/Loader'


export default function Home() {

  const router = useRouter()
  const {data: session, status} = useSession({
    onUnauthenticated(){
      router.push("/auth/signin");
    }
  })

  if(status === "loading") return (
    
    <Loader />
  )
  
  console.log(session);


  return (
    <div className="">
      <Head>
        <title>Spotify - Visakh </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://rebrand.ly/af77f9" />
      </Head>

      <Dashboard />
    </div>
  )
}
